### ISSUE TITLE
First tap in UITableView after dragging up or down is ignored

### ISSUE THREAD

**Issue by irlennard** [applidium/OverlayContainer#30]
I have found an issue where if your overlay view controller contains a table view and drives the swipe up/down, after the up/down animation is complete (after `overlayContainerViewController(containerViewController: _, willTranslateOverlay: _, transitionCoordinator: _)`) the first tap on the table view doesn't register. You need to tap again. You can also see that the scroll indicator stays visible and doesn't disappear as it should. You can see this behaviour in your example project with `BackdropExampleViewController`.

**Comment by gaetanzanella** [comment]
I'm working on it but I did not found a solution yet. Overriding the content offset of a UITableView creates a conflit with its internal gesture management.

Fun fact, it is also visible in the native Maps app.

![ezgif com-resize (3)](https://user-images.githubusercontent.com/27817228/59616195-3ffe6e80-9124-11e9-825c-57512516ff6f.gif)

**Comment by irlennard** [comment]
Ok, thanks for the info!

**Comment by gaetanzanella** [comment]
For the scroll indicator, you can hide it each time the container is dragged 

```
    func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                        willStartDraggingOverlay overlayViewController: UIViewController) {
        self.tableView.showsVerticalScrollIndicator = false
    }

    func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                        didMoveOverlay overlayViewController: UIViewController,
                                        toNotchAt index: Int) {
        self.tableView.showsVerticalScrollIndicator = true
    }
```

**Comment by gaetanzanella** [comment]
It seems to be fixed in iOS 13. I guess they changed the `UIScrollView` implementation.
