### ISSUE TITLE
Subclass OverlayContainerViewController?

### ISSUE THREAD

**Issue by gorkemg** [applidium/OverlayContainer#35]
Currently it is not possible to subclass OverlayContainerViewController, afaik.
Xcode error message: "Cannot inherit from non-open class 'OverlayContainerViewController' outside of its defining module"
This is probably due to OverlayContainerViewController being "public" and not "open". Open exists since Swift 3 and allows a class or function to be subclassed or overridden outside the current module.
It would be great if we could subclass OverlayContainerViewController for custom contained overlays.

**Comment by gaetanzanella** [comment]
It's an intentional choice. As you can see in the examples, composition is used rather than subclassing: a parent VC embeds the overlay container.
Which customisations have you in mind?

**Comment by gorkemg** [comment]
I have a transit app and like in Apple Maps, I'd like to display multiple overlays if the user selects stops or buses on the map.
Through subclassing, I can simply prepare multiple OverlayContainer classes that will look different for a stop or bus and use them in all of my existing ViewControllers by doing the following:
`            
let stopOverlay = StopOverlayViewController()
stopOverlay.stop = annotiation.stop
addChild(stopOverlay, in: view)
`
It works great and it makes it very easy to display multiple overlays on top of each other, just like in Apple Maps.

**Comment by gaetanzanella** [comment]
`StopOverlayViewController` could be a simple `UIViewController` and a parent of a `OverlayContainer` right?

**Comment by gorkemg** [comment]
I tried that, but the UIViewController doesn't let touches through. Therefore, I can't move the map behind. So I would have to handle that. That would probably not be a big issue, however, it feels hacky and subclassing seems the right way to go, imho.

**Comment by gaetanzanella** [comment]
Yes, you should use a `PassThroughView` as a root view of your view controller.

In conclusion, I don't see subclassing as required to respond to your need. You're not overriding an overlay container specific behaviour, just looking for a way to encapsulate your custom logic. I think composition is the right way to go. Even if it may seem inconvenient at first, your overlay container implementation will be hidden and you won't interfere with the overlay container internal view hierarchy.

Thanks for your issue anyway. It's great to have feedbacks 👍 .
