### ISSUE TITLE
Is there a way to define the starting notch position?

### ISSUE THREAD

**Issue by marktrobinson** [applidium/OverlayContainer#36]
Is there a way for me to specify that i want the OverlayContainerViewController to begin at notch position x e.g. if i have 3 notches, min, med, max - can i specify that i want it to start at the med notch and not the min?

Awesome library by the way!

**Comment by gaetanzanella** [comment]
Sure, does calling `moveOverlay(toNotchAt:)` in `viewDidLoad` do the trick?

**Comment by marktrobinson** [comment]
Works like a charm! Cheers @gaetanzanella
