### ISSUE TITLE
Multiple Overlay with different notches?

### ISSUE THREAD

**Issue by saltbieb** [applidium/OverlayContainer#37]
Hi,

is it possible to add multiple overlays which are nested? So I've got a background layer, a first overlay layer, and a second overlay with the special condition that the second overlay has **not** the full height of the first overlay layer and its max height is limited to 2/3 of the height of the first overlay.

I've created an image to illustrate it.

![description_notches](https://user-images.githubusercontent.com/27521008/64929609-6ec1d900-d828-11e9-9f8d-45516ec485cf.png)

Thank you.

**Comment by gaetanzanella** [comment]
Hi @saltbieb,

I've never tried it but I guess you can compose multiple overlay containers. Something like:
```
let backgroundVC = YellowVC()
let firstOverlayVC = BlueVC()
let secondOverlayVC = PinkVC()

let overlayContainerVC0 = OverlayContainerViewController()
let overlayContainerVC1 = OverlayContainerViewController()

overlayContainerVC0.viewControllers = [
    backgroundVC,
    overlayContainerVC1
]
overlayContainerVC1.viewControllers = [
   firstOverlayVC,
   secondOverlayVC
]
```
Does it work?

**Comment by saltbieb** [comment]
Hey @gaetanzanella,

thank you for your fast response. Unfortunately I didn't had the time to test it directly. Now I've managed it and it's working with your solution!

Thank you for your help.
