### ISSUE TITLE
Drawer not responding to scroll in contained scrollView when in navigationController?

### ISSUE THREAD

**Issue by sfla** [applidium/OverlayContainer#39]
I've stumbled on an issue where the drawer won't accept scrolling at all. I first discovered this because I'm trying to make this work with a CollectionView instead of a TableView, but I manage to reproduce it with tableView as well.

Reproduce: 
Open the OverlayContainer_Example-project
• AppDelegate:18, change to `window?.rootViewController = ModalNavigationViewController()`
• SearchViewController:44, insert `self.tableView.bounces = false`
Observe the following: 
![](https://i.imgur.com/3ju8Yoz.gif)

This seems to be due to `bounces=false`, since it doesn't happen without it. But this is happening to me by default with UICollectionView, even though `bounces = true`.

Also, if you now change the SearchController:58 `return 10` instead of 100, then it's actually impossible to minimize it by dragging the content, because you can't scroll up or down, due to no bouncing:
![](https://i.imgur.com/Cko2LfH.gif)
Not shown in the gif; it's still possible to move it by dragging on the searchbar-area.

So, the tableView.bounces=false makes this particular problem - but my issue is that this happens by default when I use a collectionView, and I'm not sure how to fix it. 
I did use the delegate to set the `overlayController.drivingScrollView` as in the example, which makes it scrollable. And everything is working perfectly as long as the height of the content is taller than the max notch, so scrolling can occur everywhere. But when the content size is somewhere between minimum and maximum notch, then it acts weird when dragging to max height, and won't be dragged up/down after that.

Edit; I see now that the `scrollViewDidScroll` doesn't fire when the content is maximized.. not sure how to investigate further.

**Comment by gaetanzanella** [comment]
Hi @sfla, thanks for the issue, I never thought about that case. I'll take a look. 

I guess the issue comes from the collectionView unique behavior : it doesn't scroll if its frame is larger than its content. So you're right, didScroll is not called and the overlay doesn't move. Try to set 'alwaysBounceVertical = true'.

**Comment by sfla** [comment]
Excellent! `alwaysBounceVertical = true` worked perfectly:) Thank you!
Supporting `bounces=false` is not necessary for me, just used it to reproduce the same behaviour:) You could re-open the issue if you want to keep it for that, but **my** problem is solved:)
