### ISSUE TITLE
MapsLikeViewController using SnapKit

### ISSUE THREAD

**Issue by seljabali** [applidium/OverlayContainer#40]
Hello,

First off thank you so much for this awesome library. It looks great! 😃 

I've been trying to replicate the `MapsLikeViewController.swift` [page](https://github.com/applidium/OverlayContainer/blob/master/Example/OverlayContainer_Example/Maps/MapsLikeViewController.swift) using SnapKit instead of storyboards. I got close however touches of map don't go through since the overlay container captures them, despite using the Passthrough view. 

I've created a small sample repo [here](https://github.com/seljabali/overlay-container-example). Any help would be appreciated.

Thanks,
-Sami

**Comment by gaetanzanella** [comment]
Hi! 

First of all PassThroughView is public, so you don't need to copy it. 

Note that a touch passes though a `PassThoughView` but it won't go further if this latter is inside a regular view.
I see things like:
```
let overlayBackground = PassThroughView()
let overlayContainerView = UIView()

overlayBackground.addSubview(overlayContainerView)
```
Try to use `PassThroughView` everywhere:
```
let overlayContainerView = UIView()
```
Furthermore, try to use the same VC hierarchy as the example.

**Comment by seljabali** [comment]
Thank you @gaetanzanella. Your suggestions were spot on & got them fixed! Have a great day sir!
