### ISSUE TITLE
Duration of animation for moveOverlay

### ISSUE THREAD

**Issue by sfla** [applidium/OverlayContainer#41]
This is more of a request for help than an issue, I guess, but I can't figure out how to set the duration of the animation when calling `moveOverlay(toNotchAt:,animated:)`. I even considered importing the entire OverlayContainer as classes instead of a pod so I could manipulate it if it was private, but I can't find a duration anywhere, just velocity and advanced animation protocols.
It would be nice to make it animate alongside another animation too, but I just don't understand how.
The ShowOverlayExample just uses the basic "moveOverlay" with the default duration, so it couldn't help me..

**Comment by gaetanzanella** [comment]
Hi @sfla, the overlay container CV will use the `OverlayAnimatedTransitioning` provided by its delegate to animate a translation ([ref](https://github.com/applidium/OverlayContainer#custom-translation-animations)). You can provide your own object to modify the animation implementing:
```
    func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                        transitioningDelegateForOverlay overlayViewController: UIViewController) -> OverlayTransitioningDelegate?
```
Note that by default the container uses the `SpringOverlayTranslationAnimationController` which uses this `UISpringTimingParameters` [init](https://developer.apple.com/documentation/uikit/uispringtimingparameters/1649764-initwithmass?language=objc) under the hood. So, the animation is entirely based on physics, the duration parameter is actually 0.

See [this](https://github.com/applidium/OverlayContainer#backdrop-view) to animate things alongside this overlay translation.

**Comment by sfla** [comment]
Great! Thanks. I haven't used (animateAlongside:) with transitionCoordinator and context etc. that much in the past, so I'll look into it. The challenge is that I want it the other way around; to make the overlay animate alongside another animation.

**Comment by gaetanzanella** [comment]
You can try to move the overlay without animation and call `layoutIfNeeded` on any view that contains it.  Something like:
```
UIView.animate(withDuration: 1) {
     self.overlayContainer.moveOverlay(toNotchAt: 0, animated: false)
     self.view.layoutIfNeeded()
}
```

**Comment by sfla** [comment]
Oh man. I tried that yesterday, but didn't include the `layoutIfNeeded()`, Thanks!

**Comment by pabsanmez** [comment]
Thank you! :) This has saved my day :)!
BTW @gaetanzanella this library is really really awesome! Thank you for putting so much effort on it and let the others use it :)
