### ISSUE TITLE
Unable to subclass OverlayContainerViewController. Everything is public, not open

### ISSUE THREAD

**Issue by sfla** [applidium/OverlayContainer#47]
This is more a question than an issue, sorry if it's not the right place, but I am experimenting with the container and found the need to retain some additional information/data within the container. I would like to subclass the OverlayContainerViewController (e.g `class MyCustomContainerViewController:OverlayContainerViewController`) and add my data there, as well as it would give me the opportunity to directly override other functions if needed (if the functions are changed to `open` as well).

Is there a reason this project is `public` rather than `open`?

I could just include the source files into my project to fix it (same module), but with your recent addition of Swift Package, I'd like to do it the right way.

**Comment by gaetanzanella** [comment]
See  https://github.com/applidium/OverlayContainer/issues/35

But if you make a PR, I will consider it.
