### ISSUE TITLE
`willTranslateOverlay:` isn't being called after the user stops dragging

### ISSUE THREAD

**Issue by galexite** [applidium/OverlayContainer#50]
I'm trying to fade away views when the user drags the overlay or when the overlay is travelling between notches, but `willTranslateOverlay:` doesn't appear to be called on the delegate when the user has let go of the overlay and the overlay starts travelling automatically to the nearest notch.

**Comment by gaetanzanella** [comment]
`willTranslateOverlay` is called whenever the overlay view controller is about to be translated. The translation can be animated or not. In the first case, `willTranslateOverlay` is called only once before the translation.  Do you confirm this behavior?

**Comment by galexite** [comment]
Sorry, my mistake! I must have misunderstood the documentation for that method. Yes, it is correctly only called when the animation is to begin.

Thanks!
