### ISSUE TITLE
When DrivingScrollView has bounces=false, the overlay does not respond

### ISSUE THREAD

**Issue by sfla** [applidium/OverlayContainer#51]
When using a normal overlay without a drivingScrollView, and you try to drag it too far up, it has this nice dampening effect on the entire overlay (it lets you drag it a few pixels, then bounces back). I wanted to replicate this with a tableView as content, but when dragging it too far top, the overlay stays the same (max notch) and the tableView scrolls out of bounds and bounces back. I thought maybe it would work if I disabled `bounces`, but that just makes the entire overlay unscrollable, probably because didScroll isn't called.
Is there any other way of replicating the dampening, but with scrollViews?

**Comment by gaetanzanella** [comment]
Is the content bigger than the table view's bounds?

I don't understand exactly what you want. Can you provide a video or something?

**Comment by sfla** [comment]
The left device is just a normal UIViewController in a container. When dragging it to the top notch and beyond the top, it grows slightly.

The center device is the example from your project (but with 10 elements). It has a drivingScrollView (tableView). When scrolling to the top and beyond, it simply bounces the content of the drivingScrollView. What I expect is for the entire container to bounce (just like in the left device) when the drivingScrollView has reached its bottom content.

The last device is the same as the center device, but with "bounces=false", because I assumed "bounces" was the reason the content bounced instead of the entire container growing. But, it didn't. In fact, the entire container stops responding when the content is less than the bounds and bounces=false.
I assume this is because didScroll is never called, and the drivingScrollView-logic needs it to be used?

![compared](https://user-images.githubusercontent.com/1976081/69717084-a8a63a00-110b-11ea-9013-f49694350e16.gif)

**Comment by gaetanzanella** [comment]
Thanks for the detailed answer!

In ordre to avoid conflicts, the scroll view's pan gesture will always override the one attached to the view. Does setting `isScrollEnabled = false` do the trick?
