### ISSUE TITLE
Is there a way to animate the OverlayContainer alongside another animation?

### ISSUE THREAD

**Issue by sfla** [applidium/OverlayContainer#53]
I've seen the examples/comments for how to animate another object alongside the animation of the OverlayContainer, e.g fade in backdrop based on the height of the drawer. But is there a way to animate the height of the drawer based on another animation?

In my case, I have a UINavigationController in the container, and when I navigate from one view to another (inside the container), the origin- and the destination-viewControllers may have different "preferred" notches, so I want to animate the height of the drawer to perfectly match the transition from "origin-notch" to "destination-notch" along the navigation animation. This include when the user swipes back, which is done using a transitionCoordinator and a context (e.g no set duration).

The only way I've found to go from one notch to another is to call `moveOverlay(toNotchAt:Int, animated:Bool`, which won't work in this case.

**Comment by gaetanzanella** [comment]
I guess https://github.com/applidium/OverlayContainer/issues/41#issuecomment-537830419 did not work. Why? If the containers haven't the same notches heights, you could create fake ones and disable/enable them right before the animation.

**Comment by sfla** [comment]
Because it's not an interruptible animation, I guess?

```
viewController.transitionCoordinator?.animate(alongsideTransition: { (context) in
    self.overlayContainer?.moveOverlay(toNotchAt: targetNotch, animated: false)
    viewController.backgroundColor = .green // <- This is being animated
    self.view.layoutIfNeeded()
}, completion: { (context) in
    print("Transition completed")
})
```

If I start swiping back in my contained navigationController, the overlay will instantly snap to the targetNotch. But the backgroundColor is smoothly animating back and forth between white and green if I keep swiping.

**Comment by gaetanzanella** [comment]
Is `self.view` an ancestor of the overlay container's view?

It should work. Could you provide a sample code? Your case looks interesting.
