### ISSUE TITLE
Missing param in willEndDraggingOverlay delegate call

### ISSUE THREAD

**Issue by opchronatron** [applidium/OverlayContainer#56]
In an older version, you used to pass the transitionCoordinator. I use this to match animations when the overlay is animating to a notch. Your comments still reference the transitionCoordinator but it is missing in the call function see below. 

   /// Tells the delegate when the user finishs dragging the overlay view controller with the specified velocity.
    ///
    /// - parameter containerViewController: The container requesting this information.
    /// - parameter overlayViewController: The current top overlay view controller.
    /// - parameter transitionCoordinator: The transition coordinator object associated with the translation end.
    func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                        willEndDraggingOverlay overlayViewController: UIViewController,
                                        atVelocity velocity: CGPoint)

**Comment by gaetanzanella** [comment]
Hi @opchronatron, thanks for pointing me this issue in the comments.

Use `willTranslateOverlay` instead.
```
func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                    willTranslateOverlay overlayViewController: UIViewController,
                                    transitionCoordinator: OverlayContainerTransitionCoordinator)
```
