### ISSUE TITLE
Support for top to bottom overlay

### ISSUE THREAD

**Issue by alexjameslittle** [applidium/OverlayContainer#57]
Would it be possible to support drag down overlay view with this library. I managed to achieve the desired effect by flipping the transform however as expected the pan gesture would need to be adjusted too

Do you have plans to support this?

**Comment by gaetanzanella** [comment]
hi @alexjameslittle,  "drag down overlay", what do you mean?

**Comment by alexjameslittle** [comment]
@gaetanzanella Where the drawer is at the top and you can drag the drawer down. Basically an inverted use of the Apple maps drawer. The minimised view will sit at the top of the screen and when expanded will animate down.

**Comment by gaetanzanella** [comment]
And how would the scroll view behave in such scenario?

**Comment by alexjameslittle** [comment]
It would drive the closing of the view based on scrolling to the bottom of the scroll view

**Comment by thomasdelgado** [comment]
+1 for this! Having the same behavior as the Apple Maps on landscape would be nice

**Comment by gaetanzanella** [comment]
@thomasdelgado the Maps like example reproduces this behavior, doesn't it?

**Comment by thomasdelgado** [comment]
@gaetanzanella partially I would say. Apple Maps currently allows to scroll and open the overlay from top to bottom.

https://user-images.githubusercontent.com/3489795/177822953-e5db7320-e7a9-4c30-b851-c6052c6362a7.mov

**Comment by gaetanzanella** [comment]
I see. You should implement this behavior yourself. It shouldn't be too hard: use the maps like example and add a pan gesture capable of reducing the height of your overlay container view controller.
