### ISSUE TITLE
Can you present multiple controllers over each other?

### ISSUE THREAD

**Issue by bryan1anderson** [applidium/OverlayContainer#59]
I need the ability to click on a cell in the container, and then have another container or view controller appear on top of that. I have run into issues doing with this other similar libraries so I built my own, but 2 years in and I think its time to consider other solutions

Perhaps project is the answer

**Comment by gaetanzanella** [comment]
See this [link](https://github.com/applidium/OverlayContainer#multiple-overlays). Is it what you're looking for?

**Comment by bryan1anderson** [comment]
Yes thank you. That is what I would need. I'll look over it to see how well I can use this!
