### ISSUE TITLE
SwiftUI support needed!

### ISSUE THREAD

**Issue by ramunasjurgilas** [applidium/OverlayContainer#60]
Would be very good to have SwiftUI support.

**Comment by gaetanzanella** [comment]
I thought a bit about it. SwitUI does not provide accessors to the UIKit components used under the hood. So you won't be able to set a driving scroll view for example.

What could the API look like?

**Comment by ramunasjurgilas** [comment]
I do not know how it could look. My self needs to investigate around this.

**Comment by bryan1anderson** [comment]
Could you not create some kind of delegate that simply captures the content offset? @gaetanzanella 

https://medium.com/@maxnatchanon/swiftui-how-to-get-content-offset-from-scrollview-5ce1f84603ec

**Comment by gaetanzanella** [comment]
SwiftUI support is [coming](https://github.com/applidium/OverlayContainer/tree/feature/swiftUI) 🎉 .

```swift
import SwiftUI
import OverlayContainer

struct SUIExampleView: View {

    var body: some View {
        Color.red.floatingOverlay(Color.blue)
    }
}
```
Here is the roadmap:

- [x] Create overlay modifier
- [ ] Create overlay style modifier
- [ ] Create overlay proxy to enable overlay movements
- [ ] Create overlay observer modifiers
- [ ] Create overlay layout modifiers

**Comment by gaetanzanella** [comment]
A first beta is [available](https://github.com/faberNovel/DynamicOverlay) 🎉
