### ISSUE TITLE
How to get the current container notch

### ISSUE THREAD

**Issue by zhoujun706** [applidium/OverlayContainer#63]
as title

**Comment by zhoujun706** [comment]
or notch index

**Comment by zhoujun706** [comment]
the delegate function just can get after notch index, i want to get the index before change

**Comment by gaetanzanella** [comment]
Please read the README https://github.com/applidium/OverlayContainer#tracking-the-overlay
```func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                    willMoveOverlay overlayViewController: UIViewController,
                                    toNotchAt index: Int)
```

**Comment by zhoujun706** [comment]
this function index is toNotch , i want current notch, how can i get this like containerControlloer.currentNotchIndex

**Comment by zhoujun706** [comment]
I just use moveOverlay() function, but i want recorde the notchindex before move

**Comment by zhoujun706** [comment]
thankyou

**Comment by gaetanzanella** [comment]
You have to track the current index yourself:
```
var lastNotchReached = 0

func overlayContainerViewController(_ containerViewController: OverlayContainerViewController,
                                    didMoveOverlay overlayViewController: UIViewController,
                                    toNotchAt index: Int) {
    self.lastNotchReached = index
}
``

**Comment by zhoujun706** [comment]
thanks for your reply.

I will draw a picture for you tomorrow, then you will understand . Today is too late
thanks again

**Comment by zhoujun706** [comment]
Hello , please see this:
![截屏2020-04-29 10 27 25](https://user-images.githubusercontent.com/4391944/80555883-3b713a80-8a04-11ea-897c-cc257b7b5875.png)
thank you

**Comment by gaetanzanella** [comment]
I don't understand… since your overlay moved to the top, you should have a callback. I don't see it on your image.

**Comment by zhoujun706** [comment]
For example, the KVO can get old value and new value.
And now the OverlayContainerViewControllerDelegate function just can get the new value(index),
I want the old value(index) .

Thank you : )

**Comment by gaetanzanella** [comment]
If you do https://github.com/applidium/OverlayContainer/issues/63#issuecomment-620578139, `lastNotchReached` will correspond to the previous notch index

**Comment by zhoujun706** [comment]
All right, thank you .
I solve the problem as you say, but I define a property to recorde can or not update last index.
Thank you
