### ISSUE TITLE
ConcreteOverlayContainerDismissalPolicyContext Errors

### ISSUE THREAD

**Issue by DorenBoust** [applidium/OverlayContainer#64]
Hi
way i got those errors?
(i installed with swift packages)

thanks
![image](https://user-images.githubusercontent.com/29662366/80811167-0284c180-8bce-11ea-9e0a-d5c6f52c9ffd.png)

**Comment by gaetanzanella** [comment]
Hi @DorenBoust, thanks for the issue!
A ```import UIKit``` is missing. 
3.5 is still in beta, I have to fix the CI before releasing it (to detect such errors…).
Use the version 3.4.1 instead!

**Comment by gaetanzanella** [comment]
Fix in 3.5.0-beta.3
