### ISSUE TITLE
Incorrect height for navigation bar when presenting modally

### ISSUE THREAD

**Issue by wrightak** [applidium/OverlayContainer#74]
Make the changes shown here: https://github.com/wrightak/OverlayContainer/commit/9e50c5b4527be54a79a4a6bfecfb03ffe79e53be

Then run the OverlayContainer_Example, which should already be showing the ActivityControllerPresentationLikeViewController. When presenting, the navigation bar height is incorrect. I think something might be happening with safe area insets. When you swipe to different notches, the height corrects itself and stays corrected. This only happens on the lowest notch, presenting the medium notch shows no problem.

Before swiping:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-04 at 13 34 53](https://user-images.githubusercontent.com/1816940/95007086-77a96680-0646-11eb-8c6f-ad71b14a06a3.png)

After swiping (correct height):

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-04 at 13 35 04](https://user-images.githubusercontent.com/1816940/95007087-8263fb80-0646-11eb-84d1-37732ccf4f4b.png)

**Comment by gaetanzanella** [comment]
Hi @wrightak, thanks for the detailed issue. It comes from the native safe area inset update behaviour described [here](https://github.com/applidium/OverlayContainer/blob/master/README.md#safe-area). 
Can you use the `.flexibleHeight` overlay container style?

**Comment by wrightak** [comment]
Thanks for the kind reply. I read the section of the readme that you linked to, and found the video, but I'm still not 100% understanding what's going on. I guess I need to read more. I especially don't understand why swiping up and down changes the safe area insets. And why those insets can't be corrected before swiping.

Using `.flexibleHeight` worked for me, thank you.
