### ISSUE TITLE
Could I know overlay position changes realtime

### ISSUE THREAD

**Issue by FrankWuoO** [applidium/OverlayContainer#78]
Hi there! 
I'm trying to make interaction with other views in sync with the overlay transition and maybe is same issue with #42 

Here is my implementation, I put detect point code in  

```swift 
func overlayContainerViewController(_ containerViewController: OverlayContainerViewController, willTranslateOverlay overlayViewController: UIViewController, transitionCoordinator: OverlayContainerTransitionCoordinator) {
    print("Moving")
    transitionCoordinator.animate { (context) in
    } completion: { (context) in
          let point = self.view.convert(overlayViewController.view.frame.origin, from: overlayViewController.view)
          let limit: CGFloat = kTopDistance + self.view.safeAreaInsets.top
          var offset: CGFloat = 0.0
          if point.y < limit {
              offset = limit - point.y
          }
          self.topContainerTopConstraint.constant = -offset
    }
}
```

It works fine with using finger to drag overlay, but when I slide up the overlay quickly or call `containerVC.moveOverlay(toNotchAt: 2, animated: true)`, it's jump a little bit.

I checked the code and found that delegate didn't call this method `overlayContainerViewController(_ containerViewController: OverlayContainerViewController, willTranslateOverlay overlayViewController: UIViewController, transitionCoordinator: OverlayContainerTransitionCoordinator)` continuously 

I've attached a video. 

https://user-images.githubusercontent.com/10287931/103202138-93ae6280-492c-11eb-9516-84f3ac55d1d0.mov

**Comment by gaetanzanella** [comment]
Hi @FrankWuoO

The transitions can be animated. In that case, the delegate method will be called only once. You can detect them using the `OverlayContainerTransitionCoordinator.isAnimated` property. 

I would move your logic to the `animate` block and use the `context.targetTranslationHeight` to know where the container will be:
```
func overlayContainerViewController(_ containerViewController: OverlayContainerViewController, willTranslateOverlay overlayViewController: UIViewController, transitionCoordinator: OverlayContainerTransitionCoordinator) {
    transitionCoordinator.animate { (context) in
          let offset = ... // based on `context.targetTranslationHeight`
          self.topContainerTopConstraint.constant = -offset
          if context.isAnimated {
              self.view.layoutIfNeeded()
          }
    } completion: { (context) in

    }
}
```

**Comment by FrankWuoO** [comment]
@gaetanzanella  Cool!! You save my day.
Thanks for your answer. 🙇
