### ISSUE TITLE
MainActor Support

### ISSUE THREAD

**Issue by robert-koch** [applidium/OverlayContainer#84]
**Description**
When using OverlayContainer 3.5.2 with Swift 5.5+, iOS 13+, and Xcode 13.2+, there are a number of compiler errors related to Swift actors and actor-isolation in a majority of common use cases. As an example, whenever implementing `OverlayContainerViewControllerDelegate` in a view controller, all delegate functions must be marked as `nonisolated` in order for the view controller to appropriately satisfy the protocol requirements. This, however, results in the delegate function not being able to reference any values from any main actor context within the application. 

**Expected behavior**
All classes and protocols properly conform to the appropriate actors where necessary.

**Environnement :**
 - Swift 5.5
 - Xcode 13.2.1
 - iOS 13.0+

**Additional context**
I was able to manually add the source to my project and rectify the situation by applying the `@MainActor` prefix on the necessary classes and protocols within the library, but as I am not fully versed in Swift concurrency and actors yet, I do not know if this is simply a band-aid or the appropriate way to handle the issue. I can submit a PR for the fixes if that would help.

**Comment by gaetanzanella** [comment]
Hi @robert-koch, thanks for the issue! 

I couldnt reproduce the problem. I am using Xcode 13.2.1. Could you provide a sample code?

**Comment by robert-koch** [comment]
@gaetanzanella you know what, I never thought to check that, and you are 100% correct. I appreciate the response back. Thank you much.
