### ISSUE TITLE
Should have a max width

### ISSUE THREAD

**Issue by thierrybucco** [applidium/OverlayContainer#85]
on iPad in landscape mode it would be nice to limit width.

**Comment by gaetanzanella** [comment]
Hey Thierry!

Did you take a look at the [Maps example](https://github.com/applidium/OverlayContainer/blob/master/Example/OverlayContainer_Example/Maps/MapsLikeViewController.swift)?

The max width management could be built-in, that's true but you can already easily create your own layout.

**Comment by thierrybucco** [comment]
This is perfect! Thanks Gaetan.
I am closing this ticket.
