### ISSUE TITLE
Question: How to expand OverlayContainer only after bouncing from bottom? 

### ISSUE THREAD

**Issue by thomasdelgado** [applidium/OverlayContainer#87]
Hello @gaetanzanella! 
First of all, congratulations on such an amazing and straightforward implementation! It really helps folks that can't ditch iOS 14- support :D 

I have a question: Is it possible (or how do you suggest approaching it) to make the `OverlayContainer` grow only after reaching the bottom of the `scrollView`? Currently, as soon as you start swiping up, the `OverlayContainer` starts to move. 

![IMG_C8D514D93289-1](https://user-images.githubusercontent.com/3489795/167185494-3a660c00-fcb4-4c03-959b-81255b9b8a7c.jpeg)

Thanks for your time!

**Comment by gaetanzanella** [comment]
Hi @thomasdelgado, thanks for the issue!

Sorry, but no, you can't. It is though feasible of implementing it. You could play with the [ScrollViewOverlayTranslationDriver](https://github.com/applidium/OverlayContainer/blob/master/Source/Classes/Internal/ScrollViewOverlayTranslationDriver.swift) ;).
